language: java
jdk: oraclejdk14
script:
  - mvn clean


services:
  - postgresql
addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
env:
  global:
    - PGPORT=5433
    - DB_NAME=registration
    - DB_USER=pyrax
    - DB_PASSWORD=+254Vornex

before_script:
  - psql -c "CREATE USER ${DB_USER} with encrypted password ${DB_PASSWORD};"
  - psql -c "CREATE DATABASE ${DB_NAME} WITH OWNER = ${DB_USER};"
  - psql --dbname=$DB_NAME --file=sql/create-tables.sql


deploy:
  provider: heroku
  api_key:
    secure: "6058df64-0629-4bb1-bf17-18a5d475380d"
  app: spring-reg
  on:
    branch: master
