
language: java

jdk: oraclejdk14

script: mvn clean

deploy:
  provider: heroku
  api_key:
    secure: "6058df64-0629-4bb1-bf17-18a5d475380d"
  app:
    master: spring-reg
    development: travis_db
    on: development


services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5433


postgres:
  adapter: postgresql
  database: registration
  username: postgres


